# Generated by Django 6.0.3 on 2026-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_tasks_assignee_alter_tasks_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTasks',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task_manager.tasks',),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='created', verbose_name='Статус задачи'),
        ),
    ]
