# Generated by Django 6.0.3 on 2026-04-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_educationtasks_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=64, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.projects'),
        ),
    ]
