# Generated by Django 6.0.3 on 2026-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_comments_message_alter_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments_file', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments_photo', verbose_name='Фото'),
        ),
    ]
