# Generated by Django 6.0.3 on 2026-05-30 10:54

import django.db.models.deletion
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_attachments_file_attachments_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEdit',
            fields=[
                ('tasks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_manager.tasks')),
            ],
            options={
                'abstract': False,
            },
            bases=(django.views.generic.edit.CreateView, 'task_manager.tasks'),
        ),
    ]
